volumes:
  db_data:

services:
  client:
    container_name: quackClient
    build: apps/client
    ports:
      - '8080:3000'
    restart: always

  server:
    container_name: quackServer
    build: apps/server
    ports:
      - '8081:4000'
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  db:
    container_name: quackDB
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}